apiVersion: apps/v1
kind: Deployment
metadata:
  name: '${DEPLOYMENT_GRAPH@microservice-account-config}'
  namespace: '${NAMESPACE@microservice-config}'
  labels:
    app: '${DEPLOYMENT_GRAPH@microservice-account-config}'
    moduleid: microservice-account-graph-service
    version: 1.70.2-auth-config-info
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '${DEPLOYMENT_GRAPH@microservice-account-config}'
  template:
    metadata:
      labels:
        app: '${DEPLOYMENT_GRAPH@microservice-account-config}'
    spec:
      containers:
        -
          name: app
          image: 'repoflow/microservice-account-graph-container:1.70.2-master'
          env:
            -
              name: ACCOUNT_ROUTE_GRAPH
              value: '${ROUTE_GRAPH@microservice-account-config}'
            -
              name: ACCOUNT_INTERNAL_PORT_GRAPH
              value: '${INTERNAL_PORT_GRAPH@microservice-account-config}'
            -
              name: AUTH_DATA_INTERNAL_URL
              value: '${INTERNAL_URL@microservice-auth-data-config}'
          ports:
            -
              containerPort: '${INTERNAL_PORT_GRAPH@microservice-account-config}'
